# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'AtoCash' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  #SkyFloatingTextField
  pod 'SkyFloatingLabelTextField'

  #SideMenu
  pod 'SideMenu', '~> 6.0'

  #Chart
  pod 'Charts'

  #Dropdown Menu
  pod 'RSSelectionMenu'
  
  #Toast Message
  pod 'Loaf'
  
  #Alamofire
  pod 'Alamofire','~>4.9.1'
  
  #Manage keyboard and stuff
  pod 'IQKeyboardManagerSwift'
  
#  # Pods for MyRealmProject
#    pod 'RealmSwift', '=10.1.4'
    
    pod 'DropDown'

pod 'Localize-Swift', '~> 3.2'

end
