//
// ApprovalRoleMapDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApprovalRoleMapDTO: Codable {

    public var _id: Int?
    public var approvalGroup: String?
    public var approvalGroupId: Int?
    public var role: String?
    public var roleId: Int?
    public var approvalLevel: Int?
    public var approvalLevelId: Int?
    public var employeeName: String?

    public init(_id: Int? = nil, approvalGroup: String? = nil, approvalGroupId: Int? = nil, role: String? = nil, roleId: Int? = nil, approvalLevel: Int? = nil, approvalLevelId: Int? = nil, employeeName: String? = nil) {
        self._id = _id
        self.approvalGroup = approvalGroup
        self.approvalGroupId = approvalGroupId
        self.role = role
        self.roleId = roleId
        self.approvalLevel = approvalLevel
        self.approvalLevelId = approvalLevelId
        self.employeeName = employeeName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case approvalGroup
        case approvalGroupId
        case role
        case roleId
        case approvalLevel
        case approvalLevelId
        case employeeName
    }

}
