//
// ApprovalLevelDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApprovalLevelDTO: Codable {

    public var _id: Int?
    public var level: Int?
    public var levelDesc: String?

    public init(_id: Int? = nil, level: Int? = nil, levelDesc: String? = nil) {
        self._id = _id
        self.level = level
        self.levelDesc = levelDesc
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case level
        case levelDesc
    }

}
