//
// ApprovalStatusType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ApprovalStatusType: Codable {

    public var _id: Int?
    public var status: String
    public var statusDesc: String?

    public init(_id: Int? = nil, status: String, statusDesc: String? = nil) {
        self._id = _id
        self.status = status
        self.statusDesc = statusDesc
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case status
        case statusDesc
    }

}
