//
// Body.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct Body: Codable {

    public var documents: [Data]?

    public init(documents: [Data]? = nil) {
        self.documents = documents
    }

    public enum CodingKeys: String, CodingKey { 
        case documents = "Documents"
    }

}
