//
// CashAndClaimRequestSearchModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CashAndClaimRequestSearchModel: Codable {

    public var empId: Int?
    public var pettyCashRequestId: Int?
    public var requestTypeId: Int?
    public var departmentId: Int?
    public var projectId: Int?
    public var subProjectId: Int?
    public var workTaskId: Int?
    public var recordDateFrom: Date?
    public var recordDateTo: Date?
    public var amountFrom: Double?
    public var amountTo: Double?
    public var costCenterId: Int?
    public var approvalStatusId: Int?
    public var isManager: Bool?
    public var isAccountSettled: Bool?

    public init(empId: Int? = nil, pettyCashRequestId: Int? = nil, requestTypeId: Int? = nil, departmentId: Int? = nil, projectId: Int? = nil, subProjectId: Int? = nil, workTaskId: Int? = nil, recordDateFrom: Date? = nil, recordDateTo: Date? = nil, amountFrom: Double? = nil, amountTo: Double? = nil, costCenterId: Int? = nil, approvalStatusId: Int? = nil, isManager: Bool? = nil, isAccountSettled: Bool? = nil) {
        self.empId = empId
        self.pettyCashRequestId = pettyCashRequestId
        self.requestTypeId = requestTypeId
        self.departmentId = departmentId
        self.projectId = projectId
        self.subProjectId = subProjectId
        self.workTaskId = workTaskId
        self.recordDateFrom = recordDateFrom
        self.recordDateTo = recordDateTo
        self.amountFrom = amountFrom
        self.amountTo = amountTo
        self.costCenterId = costCenterId
        self.approvalStatusId = approvalStatusId
        self.isManager = isManager
        self.isAccountSettled = isAccountSettled
    }


}
