//
// CashbalVsAdvancedVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CashbalVsAdvancedVM: Codable {

    public var curCashBal: Double?
    public var maxCashAllowed: Double?

    public init(curCashBal: Double? = nil, maxCashAllowed: Double? = nil) {
        self.curCashBal = curCashBal
        self.maxCashAllowed = maxCashAllowed
    }


}
