//
// CashAndClaimRequestSearchModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CashAndClaimRequestSearchModel: Codable {
    public var LoggedEmpId: Int?
    public var IsManager: Bool?
    public var ReporteeEmpId: Int?
    public var requestTypeId: Int?
    

    public init(LoggedEmpId: Int? = nil, IsManager: Bool? = nil, requestTypeId: Int? = nil, ReporteeEmpId: Int? = nil) {
        self.LoggedEmpId = LoggedEmpId
        self.IsManager = IsManager
        self.requestTypeId = requestTypeId
        self.ReporteeEmpId = ReporteeEmpId
    }


}
