//
// CostCenter.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CostCenter: Codable {

    public var _id: Int?
    public var costCenterCode: String
    public var costCenterDesc: String
    public var statusType: StatusType
    public var statusTypeId: Int?

    public init(_id: Int? = nil, costCenterCode: String, costCenterDesc: String, statusType: StatusType, statusTypeId: Int? = nil) {
        self._id = _id
        self.costCenterCode = costCenterCode
        self.costCenterDesc = costCenterDesc
        self.statusType = statusType
        self.statusTypeId = statusTypeId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case costCenterCode
        case costCenterDesc
        case statusType
        case statusTypeId
    }

}
