//
// CostCenterDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CostCenterDTO: Codable {

    public var _id: Int?
    public var costCenterCode: String?
    public var costCenterDesc: String?
    public var statusTypeId: Int?
    public var statusType: String?

    public init(_id: Int? = nil, costCenterCode: String? = nil, costCenterDesc: String? = nil, statusTypeId: Int? = nil, statusType: String? = nil) {
        self._id = _id
        self.costCenterCode = costCenterCode
        self.costCenterDesc = costCenterDesc
        self.statusTypeId = statusTypeId
        self.statusType = statusType
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case costCenterCode
        case costCenterDesc
        case statusTypeId
        case statusType
    }

}
