//
// CostCenterVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CostCenterVM: Codable {

    public var _id: Int?
    public var costCenterCode: String?

    public init(_id: Int? = nil, costCenterCode: String? = nil) {
        self._id = _id
        self.costCenterCode = costCenterCode
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case costCenterCode
    }

}
