//
// CurrencyTypeDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CurrencyTypeDTO: Codable {

    public var _id: Int?
    public var currencyCode: String?
    public var currencyName: String?
    public var country: String?
    public var statusTypeId: Int?

    public init(_id: Int? = nil, currencyCode: String? = nil, currencyName: String? = nil, country: String? = nil, statusTypeId: Int? = nil) {
        self._id = _id
        self.currencyCode = currencyCode
        self.currencyName = currencyName
        self.country = country
        self.statusTypeId = statusTypeId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case currencyCode
        case currencyName
        case country
        case statusTypeId
    }

}
