//
// CurrencyType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct CurrencyType: Codable {

    public var _id: Int?
    public var currencyCode: String
    public var currencyName: String
    public var country: String
    public var statusType: StatusType
    public var statusTypeId: Int?

    public init(_id: Int? = nil, currencyCode: String, currencyName: String, country: String, statusType: StatusType, statusTypeId: Int? = nil) {
        self._id = _id
        self.currencyCode = currencyCode
        self.currencyName = currencyName
        self.country = country
        self.statusType = statusType
        self.statusTypeId = statusTypeId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case currencyCode
        case currencyName
        case country
        case statusType
        case statusTypeId
    }

}
