//
// DepartmentVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DepartmentVM: Codable {

    public var _id: Int?
    public var deptName: String?
    public var deptDesc: String?

    public init(_id: Int? = nil, deptName: String? = nil, deptDesc: String? = nil) {
        self._id = _id
        self.deptName = deptName
        self.deptDesc = deptDesc
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case deptName
        case deptDesc
    }

}
