//
// DepartmentDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct DepartmentDTO: Codable {

    public var _id: Int?
    public var deptCode: String?
    public var deptName: String?
    public var costCenterId: Int?
    public var costCenter: String?
    public var statusType: String?
    public var statusTypeId: Int?

    public init(_id: Int? = nil, deptCode: String? = nil, deptName: String? = nil, costCenterId: Int? = nil, costCenter: String? = nil, statusType: String? = nil, statusTypeId: Int? = nil) {
        self._id = _id
        self.deptCode = deptCode
        self.deptName = deptName
        self.costCenterId = costCenterId
        self.costCenter = costCenter
        self.statusType = statusType
        self.statusTypeId = statusTypeId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case deptCode
        case deptName
        case costCenterId
        case costCenter
        case statusType
        case statusTypeId
    }

}
