//
// EditUserModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EditUserModel: Codable {

    public var _id: String?
    public var username: String?

    public init(_id: String? = nil, username: String? = nil) {
        self._id = _id
        self.username = username
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case username
    }

}
