//
// EmpCurrentPettyCashBalanceDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmpCurrentPettyCashBalanceDTO: Codable {

    public var _id: Int?
    public var employeeId: Int?
    public var curBalance: Double?
    public var updatedOn: Date?

    public init(_id: Int? = nil, employeeId: Int? = nil, curBalance: Double? = nil, updatedOn: Date? = nil) {
        self._id = _id
        self.employeeId = employeeId
        self.curBalance = curBalance
        self.updatedOn = updatedOn
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case employeeId
        case curBalance
        case updatedOn
    }

}
