//
// EmployeeDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmployeeDTO: Codable {

    public var _id: Int?
    public var firstName: String?
    public var middleName: String?
    public var lastName: String?
    public var fullName: String?
    public var empCode: String?
    public var bankAccount: String?
    public var bankCardNo: String?
    public var nationalID: String?
    public var passportNo: String?
    public var taxNumber: String?
    public var nationality: String?
    public var dob: Date?
    public var doj: Date?
    public var gender: String?
    public var email: String?
    public var mobileNumber: String?
    public var employmentTypeId: Int?
    public var employmentType: String?
    public var departmentId: Int?
    public var department: String?
    public var roleId: Int?
    public var jobRole: String?
    public var approvalGroupId: Int?
    public var approvalGroup: String?
    public var currencyTypeId: Int?
    public var statusTypeId: Int?
    public var statusType: String?

    public init(_id: Int? = nil, firstName: String? = nil, middleName: String? = nil, lastName: String? = nil, fullName: String? = nil, empCode: String? = nil, bankAccount: String? = nil, bankCardNo: String? = nil, nationalID: String? = nil, passportNo: String? = nil, taxNumber: String? = nil, nationality: String? = nil, dob: Date? = nil, doj: Date? = nil, gender: String? = nil, email: String? = nil, mobileNumber: String? = nil, employmentTypeId: Int? = nil, employmentType: String? = nil, departmentId: Int? = nil, department: String? = nil, roleId: Int? = nil, jobRole: String? = nil, approvalGroupId: Int? = nil, approvalGroup: String? = nil, currencyTypeId: Int? = nil, statusTypeId: Int? = nil, statusType: String? = nil) {
        self._id = _id
        self.firstName = firstName
        self.middleName = middleName
        self.lastName = lastName
        self.fullName = fullName
        self.empCode = empCode
        self.bankAccount = bankAccount
        self.bankCardNo = bankCardNo
        self.nationalID = nationalID
        self.passportNo = passportNo
        self.taxNumber = taxNumber
        self.nationality = nationality
        self.dob = dob
        self.doj = doj
        self.gender = gender
        self.email = email
        self.mobileNumber = mobileNumber
        self.employmentTypeId = employmentTypeId
        self.employmentType = employmentType
        self.departmentId = departmentId
        self.department = department
        self.roleId = roleId
        self.jobRole = jobRole
        self.approvalGroupId = approvalGroupId
        self.approvalGroup = approvalGroup
        self.currencyTypeId = currencyTypeId
        self.statusTypeId = statusTypeId
        self.statusType = statusType
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case firstName
        case middleName
        case lastName
        case fullName
        case empCode
        case bankAccount
        case bankCardNo
        case nationalID
        case passportNo
        case taxNumber
        case nationality
        case dob
        case doj
        case gender
        case email
        case mobileNumber
        case employmentTypeId
        case employmentType
        case departmentId
        case department
        case roleId
        case jobRole
        case approvalGroupId
        case approvalGroup
        case currencyTypeId
        case statusTypeId
        case statusType
    }

}
