//
// EmployeeVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmployeeVM: Codable {

    public var _id: Int?
    public var fullName: String?
    public var email: String?

    public init(_id: Int? = nil, fullName: String? = nil, email: String? = nil) {
        self._id = _id
        self.fullName = fullName
        self.email = email
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case fullName
        case email
    }

}
