//
// EmployeeSearchModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct EmployeeSearchModel: Codable {

    public var employeeId: Int?
    public var employeeName: String?
    public var empCode: String?
    public var bankAccount: String?
    public var bankCardNo: String?
    public var nationalID: String?
    public var passportNo: String?
    public var taxNumber: String?
    public var nationality: String?
    public var gender: String?
    public var email: String?
    public var mobileNumber: String?
    public var employmentTypeId: Int?
    public var employmentType: String?
    public var departmentId: Int?
    public var jobRoleId: Int?
    public var approvalGroupId: Int?
    public var statusTypeId: Int?

    public init(employeeId: Int? = nil, employeeName: String? = nil, empCode: String? = nil, bankAccount: String? = nil, bankCardNo: String? = nil, nationalID: String? = nil, passportNo: String? = nil, taxNumber: String? = nil, nationality: String? = nil, gender: String? = nil, email: String? = nil, mobileNumber: String? = nil, employmentTypeId: Int? = nil, employmentType: String? = nil, departmentId: Int? = nil, jobRoleId: Int? = nil, approvalGroupId: Int? = nil, statusTypeId: Int? = nil) {
        self.employeeId = employeeId
        self.employeeName = employeeName
        self.empCode = empCode
        self.bankAccount = bankAccount
        self.bankCardNo = bankCardNo
        self.nationalID = nationalID
        self.passportNo = passportNo
        self.taxNumber = taxNumber
        self.nationality = nationality
        self.gender = gender
        self.email = email
        self.mobileNumber = mobileNumber
        self.employmentTypeId = employmentTypeId
        self.employmentType = employmentType
        self.departmentId = departmentId
        self.jobRoleId = jobRoleId
        self.approvalGroupId = approvalGroupId
        self.statusTypeId = statusTypeId
    }


}
