//
// ExpenseReimburseRequestDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/*
 {"expenseReportTitle":"vgfvgvgv","projectId":null,"subProjectId":null,"workTaskId":null,"expensefor":"Business Area","employeeId":"10004","currencyTypeId":1,"isBusinessAreaReq":true,"expenseSubClaims":[{"expenseCategoryId":101,"invoiceNo":"1234","invoiceDate":"2022-12-10T20:00:01.166Z","expenseTypeId":1001,"expenseReimbClaimAmount":100,"location":"Madurai","vendor":"taj","description":"Madurai","taxNo":"12345","NoOfDaysDate":["2022-11-08T20:00:16.953Z","2022-12-08T20:00:16.953Z"],"isVAT":true,"tax":15,"taxAmount":15,"expStrtDate":"2022-11-08T20:00:16.953Z","expEndDate":"2022-12-08T20:00:16.953Z","expNoOfDays":31,"documentIds":"45"}]}
 */

public struct ExpenseReimburseRequestDTO: Codable {

    public var _id: Int?
    public var expenseReportTitle: String?
    public var employeeId: Int?
    public var employeeName: String?
    public var businessTypeId: Int?
    public var businessUnitId: Int?
    public var businessType: String?
    public var businessUnit: String?
    public var location: String?
    public var currencyTypeId: Int?
    public var totalClaimAmount: Double?
    public var expReimReqDate: Date?
    public var department: String?
    public var departmentId: Int?
    public var project: String?
    public var projectId: Int?
    public var subProject: String?
    public var subProjectId: Int?
    public var workTask: String?
    public var workTaskId: Int?
    public var approvalStatusTypeId: Int?
    public var approvalStatusType: String?
    public var approvedDate: Date?
    public var showEditDelete: Bool?
    public var isBusinessAreaReq: Bool?
    public var expenseSubClaims: [ExpenseSubClaimDTO]?
    public var comments: String?
    public var expensefor: String?
    public var costCenter: String?
    public var costCenterId: Int?


    public init(_id: Int? = nil, expenseReportTitle: String? = nil, employeeId: Int? = nil, employeeName: String? = nil, businessTypeId: Int? = nil,businessUnitId: Int? = nil,currencyTypeId: Int? = nil, totalClaimAmount: Double? = nil, expReimReqDate: Date? = nil, department: String? = nil, departmentId: Int? = nil, project: String? = nil, projectId: Int? = nil, subProject: String? = nil, subProjectId: Int? = nil, workTask: String? = nil, workTaskId: Int? = nil, approvalStatusTypeId: Int? = nil, approvalStatusType: String? = nil, approvedDate: Date? = nil, showEditDelete: Bool? = nil, expenseSubClaims: [ExpenseSubClaimDTO]? = nil, comments: String? = nil, expensefor: String? = nil, isBusinessAreaReq: Bool?,costCenter: String? = nil ,costCenterId: Int? = nil) {
        self._id = _id
        self.expenseReportTitle = expenseReportTitle
        self.employeeId = employeeId
        self.employeeName = employeeName
        self.businessTypeId = businessTypeId
        self.businessUnitId = businessUnitId
        self.currencyTypeId = currencyTypeId
        self.totalClaimAmount = totalClaimAmount
        self.expReimReqDate = expReimReqDate
        self.department = department
        self.departmentId = departmentId
        self.project = project
        self.projectId = projectId
        self.subProject = subProject
        self.subProjectId = subProjectId
        self.workTask = workTask
        self.workTaskId = workTaskId
        self.approvalStatusTypeId = approvalStatusTypeId
        self.approvalStatusType = approvalStatusType
        self.approvedDate = approvedDate
        self.showEditDelete = showEditDelete
        self.expenseSubClaims = expenseSubClaims
        self.comments = comments
        self.isBusinessAreaReq = isBusinessAreaReq
        self.expensefor = expensefor
        self.costCenter = costCenter
        self.costCenterId = costCenterId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case expenseReportTitle
        case employeeId
        case employeeName
        case businessTypeId
        case businessUnitId
        case businessType
        case businessUnit
        case location
        case currencyTypeId
        case totalClaimAmount
        case expReimReqDate = "requestDate"
        case department = "departmentName"
        case departmentId
        case project = "projectName"
        case projectId
        case subProject = "subProjectName"
        case subProjectId
        case workTask = "workTaskName"
        case workTaskId
        case approvalStatusTypeId
        case approvalStatusType
        case approvedDate
        case showEditDelete
        case expenseSubClaims
        case comments
        case isBusinessAreaReq
        case expensefor
        case costCenter
        case costCenterId
    }

}
