//
// ExpenseSubClaimDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ExpenseSubClaimDTO: Codable {

    public var _id: Int?
    public var employeeName: String?
    public var employeeId: Int?
    public var expenseReimbClaimAmount: Double?
    public var documentIDs: String?
    public var expReimReqDate: Date?
    public var invoiceNo: String?
    public var invoiceDate: Date?
    public var tax: Float?
    public var taxAmount: Double?
    public var vendor: String?
    public var location: String?
    public var _description: String?
    public var currencyTypeId: Int?
    public var currencyType: String?
    public var expenseTypeId: Int?
    public var expenseType: String?
    public var department: String?
    public var departmentId: Int?
    public var project: String?
    public var projectId: Int?
    public var subProject: String?
    public var subProjectId: Int?
    public var workTask: String?
    public var workTaskId: Int?
    public var approvalStatusType: String?
    public var approvalStatusTypeId: Int?
    public var approvedDate: Date?

    public init(_id: Int? = nil, employeeName: String? = nil, employeeId: Int? = nil, expenseReimbClaimAmount: Double? = nil, documentIDs: String? = nil, expReimReqDate: Date? = nil, invoiceNo: String? = nil, invoiceDate: Date? = nil, tax: Float? = nil, taxAmount: Double? = nil, vendor: String? = nil, location: String? = nil, _description: String? = nil, currencyTypeId: Int? = nil, currencyType: String? = nil, expenseTypeId: Int? = nil, expenseType: String? = nil, department: String? = nil, departmentId: Int? = nil, project: String? = nil, projectId: Int? = nil, subProject: String? = nil, subProjectId: Int? = nil, workTask: String? = nil, workTaskId: Int? = nil, approvalStatusType: String? = nil, approvalStatusTypeId: Int? = nil, approvedDate: Date? = nil) {
        self._id = _id
        self.employeeName = employeeName
        self.employeeId = employeeId
        self.expenseReimbClaimAmount = expenseReimbClaimAmount
        self.documentIDs = documentIDs
        self.expReimReqDate = expReimReqDate
        self.invoiceNo = invoiceNo
        self.invoiceDate = invoiceDate
        self.tax = tax
        self.taxAmount = taxAmount
        self.vendor = vendor
        self.location = location
        self._description = _description
        self.currencyTypeId = currencyTypeId
        self.currencyType = currencyType
        self.expenseTypeId = expenseTypeId
        self.expenseType = expenseType
        self.department = department
        self.departmentId = departmentId
        self.project = project
        self.projectId = projectId
        self.subProject = subProject
        self.subProjectId = subProjectId
        self.workTask = workTask
        self.workTaskId = workTaskId
        self.approvalStatusType = approvalStatusType
        self.approvalStatusTypeId = approvalStatusTypeId
        self.approvedDate = approvedDate
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case employeeName
        case employeeId
        case expenseReimbClaimAmount
        case documentIDs
        case expReimReqDate
        case invoiceNo
        case invoiceDate
        case tax
        case taxAmount
        case vendor
        case location
        case _description = "description"
        case currencyTypeId
        case currencyType
        case expenseTypeId
        case expenseType
        case department
        case departmentId
        case project
        case projectId
        case subProject
        case subProjectId
        case workTask
        case workTaskId
        case approvalStatusType
        case approvalStatusTypeId
        case approvedDate
    }

}
