//
// ExpenseSubClaim.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

/*
 {"expenseReportTitle":"vgfvgvgv","projectId":null,"subProjectId":null,"workTaskId":null,"expensefor":"Business Area","employeeId":"10004","currencyTypeId":1,"isBusinessAreaReq":true,"expenseSubClaims":[{"expenseCategoryId":101,"invoiceNo":"1234","invoiceDate":"2022-12-10T20:00:01.166Z","expenseTypeId":1001,"expenseReimbClaimAmount":100,"location":"Madurai","vendor":"taj","description":"Madurai","taxNo":"12345","NoOfDaysDate":["2022-11-08T20:00:16.953Z","2022-12-08T20:00:16.953Z"],"isVAT":true,"tax":15,"taxAmount":15,"expStrtDate":"2022-11-08T20:00:16.953Z","expEndDate":"2022-12-08T20:00:16.953Z","expNoOfDays":31,"documentIds":"45"}]}
 */

public struct ExpenseSubClaim: Codable {

    public var _id: Int?
    public var expenseReimburseRequest: ExpenseReimburseRequest
    public var expenseReimburseRequestId: Int?
    public var expenseType: ExpenseType
    public var expenseTypeId: Int?
    public var expenseReimbClaimAmount: Double
    public var documentIDs: String?
    public var invoiceNo: String
    public var tax: Float
    public var taxAmount: Double
    public var invoiceDate: Date
    public var vendor: String
    public var location: String
    public var _description: String

    public init(_id: Int? = nil, expenseReimburseRequest: ExpenseReimburseRequest, expenseReimburseRequestId: Int? = nil, expenseType: ExpenseType, expenseTypeId: Int? = nil, expenseReimbClaimAmount: Double, documentIDs: String? = nil, invoiceNo: String, tax: Float, taxAmount: Double, invoiceDate: Date, vendor: String, location: String, _description: String) {
        self._id = _id
        self.expenseReimburseRequest = expenseReimburseRequest
        self.expenseReimburseRequestId = expenseReimburseRequestId
        self.expenseType = expenseType
        self.expenseTypeId = expenseTypeId
        self.expenseReimbClaimAmount = expenseReimbClaimAmount
        self.documentIDs = documentIDs
        self.invoiceNo = invoiceNo
        self.tax = tax
        self.taxAmount = taxAmount
        self.invoiceDate = invoiceDate
        self.vendor = vendor
        self.location = location
        self._description = _description
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case expenseReimburseRequest
        case expenseReimburseRequestId
        case expenseType
        case expenseTypeId
        case expenseReimbClaimAmount
        case documentIDs
        case invoiceNo
        case tax
        case taxAmount
        case invoiceDate
        case vendor
        case location
        case _description = "description"
    }

}
