//
// FileDocumentDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct FileDocumentDTO: Codable {

    public var _id: Int?
    public var actualFileName: String?

    public init(_id: Int? = nil, actualFileName: String? = nil) {
        self._id = _id
        self.actualFileName = actualFileName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case actualFileName
    }

}
