//
// GetEmployeesForProject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct GetEmployeesForProject: Codable {

    public var employeeId: Int?
    public var employeeName: String?
    public var isAssigned: Bool?

    public init(employeeId: Int? = nil, employeeName: String? = nil, isAssigned: Bool? = nil) {
        self.employeeId = employeeId
        self.employeeName = employeeName
        self.isAssigned = isAssigned
    }


}
