//
// LoginModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct LoginModel: Codable {

    public var email: String?
    public var password: String?
    public var rememberMe: Bool?

    public init(email: String? = nil, password: String? = nil, rememberMe: Bool? = nil) {
        self.email = email
        self.password = password
        self.rememberMe = rememberMe
    }


}
