//
// PettyCashRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct PettyCashRequest: Codable {

    public var _id: Int?
    public var employee: Employee
    public var employeeId: Int?
    public var pettyClaimAmount: Double
    public var pettyClaimRequestDesc: String
    public var cashReqDate: Date
    public var currencyType: CurrencyType
    public var currencyTypeId: Int?
    public var department: Department?
    public var departmentId: Int?
    public var project: Project?
    public var projectId: Int?
    public var subProject: SubProject?
    public var subProjectId: Int?
    public var workTask: WorkTask?
    public var workTaskId: Int?
    public var approvalStatusType: ApprovalStatusType
    public var approvalStatusTypeId: Int?
    public var approvedDate: Date?
    public var comments: String

    public init(_id: Int? = nil, employee: Employee, employeeId: Int? = nil, pettyClaimAmount: Double, pettyClaimRequestDesc: String, cashReqDate: Date, currencyType: CurrencyType, currencyTypeId: Int? = nil, department: Department? = nil, departmentId: Int? = nil, project: Project? = nil, projectId: Int? = nil, subProject: SubProject? = nil, subProjectId: Int? = nil, workTask: WorkTask? = nil, workTaskId: Int? = nil, approvalStatusType: ApprovalStatusType, approvalStatusTypeId: Int? = nil, approvedDate: Date? = nil, comments: String) {
        self._id = _id
        self.employee = employee
        self.employeeId = employeeId
        self.pettyClaimAmount = pettyClaimAmount
        self.pettyClaimRequestDesc = pettyClaimRequestDesc
        self.cashReqDate = cashReqDate
        self.currencyType = currencyType
        self.currencyTypeId = currencyTypeId
        self.department = department
        self.departmentId = departmentId
        self.project = project
        self.projectId = projectId
        self.subProject = subProject
        self.subProjectId = subProjectId
        self.workTask = workTask
        self.workTaskId = workTaskId
        self.approvalStatusType = approvalStatusType
        self.approvalStatusTypeId = approvalStatusTypeId
        self.approvedDate = approvedDate
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case employee
        case employeeId
        case pettyClaimAmount
        case pettyClaimRequestDesc
        case cashReqDate
        case currencyType
        case currencyTypeId
        case department
        case departmentId
        case project
        case projectId
        case subProject
        case subProjectId
        case workTask
        case workTaskId
        case approvalStatusType
        case approvalStatusTypeId
        case approvedDate
        case comments
    }

}
