//
// ProjectManagementDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProjectManagementDTO: Codable {

    public var _id: Int?
    public var projectId: Int?
    public var projectName: String?
    public var employeeId: Int?
    public var employeeName: String?

    public init(_id: Int? = nil, projectId: Int? = nil, projectName: String? = nil, employeeId: Int? = nil, employeeName: String? = nil) {
        self._id = _id
        self.projectId = projectId
        self.projectName = projectName
        self.employeeId = employeeId
        self.employeeName = employeeName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case projectId
        case projectName
        case employeeId
        case employeeName
    }

}
