//
// ProjectVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProjectVM: Codable {

    public var _id: Int?
    public var projectName: String?

    public init(_id: Int? = nil, projectName: String? = nil) {
        self._id = _id
        self.projectName = projectName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case projectName
    }

}
