//
// ProjectDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public struct BusinessUnitDTO: Codable {
    
    public var businessTypeId: Int?
    public var empId: String?
    public init(businessTypeId: Int? = nil, empId: String? = nil) {
        self.businessTypeId = businessTypeId
        self.empId = empId
    }
    public enum CodingKeys: String, CodingKey {
        case businessTypeId = "businessTypeId"
        case empId = "empId"
    }
}

public struct ProjectDTO: Codable {

    public var _id: Int?
    public var projectName: String?
    public var costCenterId: Int?
    public var costCenter: String?
    public var projectManagerId: Int?
    public var projectManager: String?
    public var projectDesc: String?
    public var statusTypeId: Int?
    public var statusType: String?

    public init(_id: Int? = nil, projectName: String? = nil, costCenterId: Int? = nil, costCenter: String? = nil, projectManagerId: Int? = nil, projectManager: String? = nil, projectDesc: String? = nil, statusTypeId: Int? = nil, statusType: String? = nil) {
        self._id = _id
        self.projectName = projectName
        self.costCenterId = costCenterId
        self.costCenter = costCenter
        self.projectManagerId = projectManagerId
        self.projectManager = projectManager
        self.projectDesc = projectDesc
        self.statusTypeId = statusTypeId
        self.statusType = statusType
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case projectName
        case costCenterId
        case costCenter
        case projectManagerId
        case projectManager
        case projectDesc
        case statusTypeId
        case statusType
    }

}
