//
// ProjectManagement.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ProjectManagement: Codable {

    public var _id: Int?
    public var project: Project
    public var projectId: Int?
    public var employee: Employee
    public var employeeId: Int?

    public init(_id: Int? = nil, project: Project, projectId: Int? = nil, employee: Employee, employeeId: Int? = nil) {
        self._id = _id
        self.project = project
        self.projectId = projectId
        self.employee = employee
        self.employeeId = employeeId
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case project
        case projectId
        case employee
        case employeeId
    }

}
