//
// RequestTypeVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestTypeVM: Codable {

    public var _id: Int?
    public var requestName: String?

    public init(_id: Int? = nil, requestName: String? = nil) {
        self._id = _id
        self.requestName = requestName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case requestName
    }

}
