//
// RequestType.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RequestType: Codable {

    public var _id: Int?
    public var requestName: String
    public var requestTypeDesc: String

    public init(_id: Int? = nil, requestName: String, requestTypeDesc: String) {
        self._id = _id
        self.requestName = requestName
        self.requestTypeDesc = requestTypeDesc
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case requestName
        case requestTypeDesc
    }

}
