//
// ResetPasswordVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct ResetPasswordVM: Codable {

    public var email: String
    public var password: String
    public var token: String?

    public init(email: String, password: String, token: String? = nil) {
        self.email = email
        self.password = password
        self.token = token
    }


}
