//
// RoleToUserSearch.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoleToUserSearch: Codable {

    public var roleId: String?

    public init(roleId: String? = nil) {
        self.roleId = roleId
    }


}
