//
// RoleModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct RoleModel: Codable {

    public var roleName: String?

    public init(roleName: String? = nil) {
        self.roleName = roleName
    }


}
