//
// StatusTypeVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct StatusTypeVM: Codable {

    public var _id: Int?
    public var status: String?

    public init(_id: Int? = nil, status: String? = nil) {
        self._id = _id
        self.status = status
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case status
    }

}
