//
// SubProjectDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubProjectDTO: Codable {

    public var _id: Int?
    public var projectId: Int?
    public var projectName: String?
    public var subProjectName: String?
    public var subProjectDesc: String?

    public init(_id: Int? = nil, projectId: Int? = nil, projectName: String? = nil, subProjectName: String? = nil, subProjectDesc: String? = nil) {
        self._id = _id
        self.projectId = projectId
        self.projectName = projectName
        self.subProjectName = subProjectName
        self.subProjectDesc = subProjectDesc
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case projectId
        case projectName
        case subProjectName
        case subProjectDesc
    }

}
