//
// SubProject.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct SubProject: Codable {

    public var _id: Int?
    public var project: Project
    public var projectId: Int?
    public var subProjectName: String
    public var subProjectDesc: String

    public init(_id: Int? = nil, project: Project, projectId: Int? = nil, subProjectName: String, subProjectDesc: String) {
        self._id = _id
        self.project = project
        self.projectId = projectId
        self.subProjectName = subProjectName
        self.subProjectDesc = subProjectDesc
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case project
        case projectId
        case subProjectName
        case subProjectDesc
    }

}
