//
// TravelApprovalRequest.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct TravelApprovalRequest: Codable {

    public var _id: Int?
    public var employee: Employee
    public var employeeId: Int?
    public var travelStartDate: Date
    public var travelEndDate: Date
    public var travelPurpose: String
    public var reqRaisedDate: Date
    public var department: Department?
    public var departmentId: Int?
    public var project: Project?
    public var projectId: Int?
    public var subProject: SubProject?
    public var subProjectId: Int?
    public var workTask: WorkTask?
    public var workTaskId: Int?
    public var costCenter: CostCenter
    public var costCenterId: Int?
    public var approvalStatusType: ApprovalStatusType
    public var approvalStatusTypeId: Int?
    public var approvedDate: Date?
    public var comments: String

    public init(_id: Int? = nil, employee: Employee, employeeId: Int? = nil, travelStartDate: Date, travelEndDate: Date, travelPurpose: String, reqRaisedDate: Date, department: Department? = nil, departmentId: Int? = nil, project: Project? = nil, projectId: Int? = nil, subProject: SubProject? = nil, subProjectId: Int? = nil, workTask: WorkTask? = nil, workTaskId: Int? = nil, costCenter: CostCenter, costCenterId: Int? = nil, approvalStatusType: ApprovalStatusType, approvalStatusTypeId: Int? = nil, approvedDate: Date? = nil, comments: String) {
        self._id = _id
        self.employee = employee
        self.employeeId = employeeId
        self.travelStartDate = travelStartDate
        self.travelEndDate = travelEndDate
        self.travelPurpose = travelPurpose
        self.reqRaisedDate = reqRaisedDate
        self.department = department
        self.departmentId = departmentId
        self.project = project
        self.projectId = projectId
        self.subProject = subProject
        self.subProjectId = subProjectId
        self.workTask = workTask
        self.workTaskId = workTaskId
        self.costCenter = costCenter
        self.costCenterId = costCenterId
        self.approvalStatusType = approvalStatusType
        self.approvalStatusTypeId = approvalStatusTypeId
        self.approvedDate = approvedDate
        self.comments = comments
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case employee
        case employeeId
        case travelStartDate
        case travelEndDate
        case travelPurpose
        case reqRaisedDate
        case department
        case departmentId
        case project
        case projectId
        case subProject
        case subProjectId
        case workTask
        case workTaskId
        case costCenter
        case costCenterId
        case approvalStatusType
        case approvalStatusTypeId
        case approvedDate
        case comments
    }

}
