//
// UserToRoleModel.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct UserToRoleModel: Codable {

    public var userId: String?
    public var roleIds: [String]?

    public init(userId: String? = nil, roleIds: [String]? = nil) {
        self.userId = userId
        self.roleIds = roleIds
    }


}
