//
// WorkTask.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorkTask: Codable {

    public var _id: Int?
    public var subProject: SubProject
    public var subProjectId: Int?
    public var taskName: String
    public var taskDesc: String

    public init(_id: Int? = nil, subProject: SubProject, subProjectId: Int? = nil, taskName: String, taskDesc: String) {
        self._id = _id
        self.subProject = subProject
        self.subProjectId = subProjectId
        self.taskName = taskName
        self.taskDesc = taskDesc
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case subProject
        case subProjectId
        case taskName
        case taskDesc
    }

}
