//
// WorkTaskVM.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



public struct WorkTaskVM: Codable {

    public var _id: Int?
    public var taskName: String?

    public init(_id: Int? = nil, taskName: String? = nil) {
        self._id = _id
        self.taskName = taskName
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case taskName
    }

}
