//
// ExpenseSubClaimDTO.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation

//{id: 1, vatPercentage: 15}
public struct ExpenseVATDTO: Codable{
    public var _id: Int?
    public var vatPercentage: Int?
    public init(_id: Int? = nil, vatPercentage: Int? = nil){
        self._id = _id
        self.vatPercentage = vatPercentage
    }
    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case vatPercentage
    }
}
public struct ExpenseBusinessCategoryDTO: Codable{
    public var _id: Int?
    public var expenseTypeName: String?
    public init(_id: Int? = nil, expenseTypeName: String? = nil){
        self._id = _id
        self.expenseTypeName = expenseTypeName
    }
    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case expenseTypeName
    }
}
//{id: 101, expenseCategoryName: "Store:Store"}
public struct ExpenseBusinessDTO: Codable{
    public var _id: Int?
    public var expenseCategoryName: String?
    public init(_id: Int? = nil, expenseCategoryName: String? = nil){
        self._id = _id
        self.expenseCategoryName = expenseCategoryName
    }
    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case expenseCategoryName
    }
}
public struct ExpenseVendorDTO: Codable{
    public var _id: Int?
    public var vendorName: String?
    public init(_id: Int? = nil, vendorName: String? = nil){
        self._id = _id
        self.vendorName = vendorName
    }
    public enum CodingKeys: String, CodingKey {
        case _id = "id"
        case vendorName
    }
}
/*
 [{"expenseCategoryId":101,"invoiceNo":"1234","invoiceDate":"2022-12-10T20:00:01.166Z","expenseTypeId":1001,"expenseReimbClaimAmount":100,"location":"Madurai","vendor":"taj","description":"Madurai","taxNo":"12345","NoOfDaysDate":["2022-11-08T20:00:16.953Z","2022-12-08T20:00:16.953Z"],"isVAT":true,"tax":15,"taxAmount":15,"expStrtDate":"2022-11-08T20:00:16.953Z","expEndDate":"2022-12-08T20:00:16.953Z","expNoOfDays":31,"documentIds":"45"}]
 */
public struct ExpenseSubClaimDTO: Codable {

    public var _id: Int?
    public var employeeName: String?
    public var employeeId: Int?
    public var expenseReimbClaimAmount: Double?
    public var documentIDs: String?
    public var expReimReqDate: Date?
    public var invoiceNo: String?
    public var invoiceDate: Date?
    public var tax: Float?
    public var taxAmount: Double?
    public var vendor: String?
    public var location: String?
    public var _description: String?
    public var currencyTypeId: Int?
    public var currencyType: String?
    public var expenseTypeId: Int?
    public var expenseType: String?
    public var department: String?
    public var departmentId: Int?
    public var project: String?
    public var projectId: Int?
    public var subProject: String?
    public var subProjectId: Int?
    public var workTask: String?
    public var workTaskId: Int?
    public var approvalStatusType: String?
    public var approvalStatusTypeId: Int?
    public var approvedDate: Date?
    
    public var expenseCategoryId: Int?
    public var taxNo: String?
    public var NoOfDaysDate: [Date?]?
    public var isVAT: Bool?
    public var expStrtDate: Date?
    public var expEndDate: Date?
    public var expNoOfDays: Int?
    public var vendorId: Int?
    public var additionalVendor: String?
    public var costCenterId: Int?
    public var costCenter: String?
    
    
    

    public init(_id: Int? = nil, employeeName: String? = nil, employeeId: Int? = nil, expenseReimbClaimAmount: Double? = nil, documentIDs: String? = nil, expReimReqDate: Date? = nil, invoiceNo: String? = nil, invoiceDate: Date? = nil, tax: Float? = nil, taxAmount: Double? = nil, vendor: String? = nil, location: String? = nil, _description: String? = nil, currencyTypeId: Int? = nil, currencyType: String? = nil, expenseTypeId: Int? = nil, expenseType: String? = nil, department: String? = nil, departmentId: Int? = nil, project: String? = nil, projectId: Int? = nil, subProject: String? = nil, subProjectId: Int? = nil, workTask: String? = nil, workTaskId: Int? = nil, approvalStatusType: String? = nil, approvalStatusTypeId: Int? = nil, approvedDate: Date? = nil, expenseCategoryId: Int? = nil,taxNo: String? = nil, NoOfDaysDate: [Date?]? = nil,isVAT: Bool? = nil,expStrtDate: Date? = nil,expEndDate: Date? = nil, expNoOfDays: Int?,vendorId: Int?,additionalVendor: String?) {
        self._id = _id
        self.employeeName = employeeName
        self.employeeId = employeeId
        self.expenseReimbClaimAmount = expenseReimbClaimAmount
        self.documentIDs = documentIDs
        self.expReimReqDate = expReimReqDate
        self.invoiceNo = invoiceNo
        self.invoiceDate = invoiceDate
        self.tax = tax
        self.taxAmount = taxAmount
        self.vendor = vendor
        self.location = location
        self._description = _description
        self.currencyTypeId = currencyTypeId
        self.currencyType = currencyType
        self.expenseTypeId = expenseTypeId
        self.expenseType = expenseType
        self.department = department
        self.departmentId = departmentId
        self.project = project
        self.projectId = projectId
        self.subProject = subProject
        self.subProjectId = subProjectId
        self.workTask = workTask
        self.workTaskId = workTaskId
        self.approvalStatusType = approvalStatusType
        self.approvalStatusTypeId = approvalStatusTypeId
        self.approvedDate = approvedDate
        self.expenseCategoryId = expenseCategoryId
        self.taxNo = taxNo
        self.NoOfDaysDate = NoOfDaysDate
        self.isVAT = isVAT
        self.expStrtDate = expStrtDate
        self.expEndDate = expEndDate
        self.expNoOfDays = expNoOfDays
        self.vendorId = vendorId
        self.additionalVendor =  additionalVendor
    }

    public enum CodingKeys: String, CodingKey { 
        case _id = "id"
        case employeeName
        case employeeId
        case expenseReimbClaimAmount
        case documentIDs
        case expReimReqDate
        case invoiceNo
        case invoiceDate
        case tax
        case taxAmount
        case vendor
        case location
        case _description = "description"
        case currencyTypeId
        case currencyType
        case expenseTypeId
        case expenseType
        case department
        case departmentId
        case project
        case projectId
        case subProject
        case subProjectId
        case workTask
        case workTaskId
        case approvalStatusType
        case approvalStatusTypeId
        case approvedDate
        
        case expenseCategoryId
        case taxNo
        case NoOfDaysDate
        case isVAT
        case expStrtDate = "expStrtDate"
        case expEndDate = "expEndDate"
        case expNoOfDays
        case vendorId
        case additionalVendor
        case costCenterId
        case costCenter
        
    }

}
