//
// ApprovalStatusTypesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ApprovalStatusTypesAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalStatusTypesGet(completion: @escaping ((_ data: [ApprovalStatusType]?,_ error: Error?) -> Void)) {
        apiApprovalStatusTypesGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/ApprovalStatusTypes
     - 

     - examples: [{contentType=application/json, example=[ {
  "statusDesc" : "statusDesc",
  "id" : 0,
  "status" : "status"
}, {
  "statusDesc" : "statusDesc",
  "id" : 0,
  "status" : "status"
} ]}]

     - returns: RequestBuilder<[ApprovalStatusType]> 
     */
    open class func apiApprovalStatusTypesGetWithRequestBuilder() -> RequestBuilder<[ApprovalStatusType]> {
        let path = "/api/ApprovalStatusTypes"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[ApprovalStatusType]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalStatusTypesIdDelete(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiApprovalStatusTypesIdDeleteWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /api/ApprovalStatusTypes/{id}
     - 

     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func apiApprovalStatusTypesIdDeleteWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/api/ApprovalStatusTypes/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalStatusTypesIdGet(_id: Int, completion: @escaping ((_ data: ApprovalStatusType?,_ error: Error?) -> Void)) {
        apiApprovalStatusTypesIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/ApprovalStatusTypes/{id}
     - 

     - examples: [{contentType=application/json, example={
  "statusDesc" : "statusDesc",
  "id" : 0,
  "status" : "status"
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<ApprovalStatusType> 
     */
    open class func apiApprovalStatusTypesIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<ApprovalStatusType> {
        var path = "/api/ApprovalStatusTypes/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApprovalStatusType>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalStatusTypesIdPut(_id: Int, body: ApprovalStatusType? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiApprovalStatusTypesIdPutWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PUT /api/ApprovalStatusTypes/{id}
     - 

     - parameter _id: (path)  
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiApprovalStatusTypesIdPutWithRequestBuilder(_id: Int, body: ApprovalStatusType? = nil) -> RequestBuilder<Void> {
        var path = "/api/ApprovalStatusTypes/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalStatusTypesPost(body: ApprovalStatusType? = nil, completion: @escaping ((_ data: ApprovalStatusType?,_ error: Error?) -> Void)) {
        apiApprovalStatusTypesPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/ApprovalStatusTypes
     - 

     - examples: [{contentType=application/json, example={
  "statusDesc" : "statusDesc",
  "id" : 0,
  "status" : "status"
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<ApprovalStatusType> 
     */
    open class func apiApprovalStatusTypesPostWithRequestBuilder(body: ApprovalStatusType? = nil) -> RequestBuilder<ApprovalStatusType> {
        let path = "/api/ApprovalStatusTypes"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApprovalStatusType>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
