//
// ApprovalGroupsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ApprovalGroupsAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalGroupsApprovalGroupsForDropdownGet(completion: @escaping ((_ data: [ApprovalGroupVM]?,_ error: Error?) -> Void)) {
        apiApprovalGroupsApprovalGroupsForDropdownGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/ApprovalGroups/ApprovalGroupsForDropdown
     - 

     - examples: [{contentType=application/json, example=[ {
  "approvalGroupCode" : "approvalGroupCode",
  "id" : 0
}, {
  "approvalGroupCode" : "approvalGroupCode",
  "id" : 0
} ]}]

     - returns: RequestBuilder<[ApprovalGroupVM]> 
     */
    open class func apiApprovalGroupsApprovalGroupsForDropdownGetWithRequestBuilder() -> RequestBuilder<[ApprovalGroupVM]> {
        let path = "/api/ApprovalGroups/ApprovalGroupsForDropdown"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[ApprovalGroupVM]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalGroupsDeleteApprovalGroupIdDelete(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiApprovalGroupsDeleteApprovalGroupIdDeleteWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /api/ApprovalGroups/DeleteApprovalGroup/{id}
     - 

     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func apiApprovalGroupsDeleteApprovalGroupIdDeleteWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/api/ApprovalGroups/DeleteApprovalGroup/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalGroupsGetApprovalGroupIdGet(_id: Int, completion: @escaping ((_ data: ApprovalGroup?,_ error: Error?) -> Void)) {
        apiApprovalGroupsGetApprovalGroupIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/ApprovalGroups/GetApprovalGroup/{id}
     - 

     - examples: [{contentType=application/json, example={
  "approvalGroupDesc" : "approvalGroupDesc",
  "approvalGroupCode" : "approvalGroupCode",
  "id" : 0
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<ApprovalGroup> 
     */
    open class func apiApprovalGroupsGetApprovalGroupIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<ApprovalGroup> {
        var path = "/api/ApprovalGroups/GetApprovalGroup/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApprovalGroup>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalGroupsGetApprovalGroupsGet(completion: @escaping ((_ data: [ApprovalGroup]?,_ error: Error?) -> Void)) {
        apiApprovalGroupsGetApprovalGroupsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/ApprovalGroups/GetApprovalGroups
     - 

     - examples: [{contentType=application/json, example=[ {
  "approvalGroupDesc" : "approvalGroupDesc",
  "approvalGroupCode" : "approvalGroupCode",
  "id" : 0
}, {
  "approvalGroupDesc" : "approvalGroupDesc",
  "approvalGroupCode" : "approvalGroupCode",
  "id" : 0
} ]}]

     - returns: RequestBuilder<[ApprovalGroup]> 
     */
    open class func apiApprovalGroupsGetApprovalGroupsGetWithRequestBuilder() -> RequestBuilder<[ApprovalGroup]> {
        let path = "/api/ApprovalGroups/GetApprovalGroups"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[ApprovalGroup]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalGroupsPostApprovalGroupPost(body: ApprovalGroup? = nil, completion: @escaping ((_ data: ApprovalGroup?,_ error: Error?) -> Void)) {
        apiApprovalGroupsPostApprovalGroupPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/ApprovalGroups/PostApprovalGroup
     - 

     - examples: [{contentType=application/json, example={
  "approvalGroupDesc" : "approvalGroupDesc",
  "approvalGroupCode" : "approvalGroupCode",
  "id" : 0
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<ApprovalGroup> 
     */
    open class func apiApprovalGroupsPostApprovalGroupPostWithRequestBuilder(body: ApprovalGroup? = nil) -> RequestBuilder<ApprovalGroup> {
        let path = "/api/ApprovalGroups/PostApprovalGroup"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApprovalGroup>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path)  
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalGroupsPutApprovalGroupIdPut(_id: Int, body: ApprovalGroupDTO? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiApprovalGroupsPutApprovalGroupIdPutWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PUT /api/ApprovalGroups/PutApprovalGroup/{id}
     - 

     - parameter _id: (path)  
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiApprovalGroupsPutApprovalGroupIdPutWithRequestBuilder(_id: Int, body: ApprovalGroupDTO? = nil) -> RequestBuilder<Void> {
        var path = "/api/ApprovalGroups/PutApprovalGroup/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
