//
// ApprovalLevelsAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class ApprovalLevelsAPI {
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalLevelsGet(completion: @escaping ((_ data: [ApprovalLevelDTO]?,_ error: Error?) -> Void)) {
        apiApprovalLevelsGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/ApprovalLevels
     - 

     - examples: [{contentType=application/json, example=[ {
  "level" : 6,
  "levelDesc" : "levelDesc",
  "id" : 0
}, {
  "level" : 6,
  "levelDesc" : "levelDesc",
  "id" : 0
} ]}]

     - returns: RequestBuilder<[ApprovalLevelDTO]> 
     */
    open class func apiApprovalLevelsGetWithRequestBuilder() -> RequestBuilder<[ApprovalLevelDTO]> {
        let path = "/api/ApprovalLevels"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[ApprovalLevelDTO]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalLevelsIdDelete(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiApprovalLevelsIdDeleteWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /api/ApprovalLevels/{id}
     - 

     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func apiApprovalLevelsIdDeleteWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/api/ApprovalLevels/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalLevelsIdGet(_id: Int, completion: @escaping ((_ data: ApprovalLevelDTO?,_ error: Error?) -> Void)) {
        apiApprovalLevelsIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/ApprovalLevels/{id}
     - 

     - examples: [{contentType=application/json, example={
  "level" : 6,
  "levelDesc" : "levelDesc",
  "id" : 0
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<ApprovalLevelDTO> 
     */
    open class func apiApprovalLevelsIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<ApprovalLevelDTO> {
        var path = "/api/ApprovalLevels/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApprovalLevelDTO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalLevelsIdPut(_id: Int, body: ApprovalLevelDTO? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiApprovalLevelsIdPutWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PUT /api/ApprovalLevels/{id}
     - 

     - parameter _id: (path)  
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiApprovalLevelsIdPutWithRequestBuilder(_id: Int, body: ApprovalLevelDTO? = nil) -> RequestBuilder<Void> {
        var path = "/api/ApprovalLevels/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiApprovalLevelsPost(body: ApprovalLevelDTO? = nil, completion: @escaping ((_ data: ApprovalLevel?,_ error: Error?) -> Void)) {
        apiApprovalLevelsPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/ApprovalLevels
     - 

     - examples: [{contentType=application/json, example={
  "level" : 6,
  "levelDesc" : "levelDesc",
  "id" : 0
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<ApprovalLevel> 
     */
    open class func apiApprovalLevelsPostWithRequestBuilder(body: ApprovalLevelDTO? = nil) -> RequestBuilder<ApprovalLevel> {
        let path = "/api/ApprovalLevels"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<ApprovalLevel>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
