//
// EmpCurrentPettyCashBalancesAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class EmpCurrentPettyCashBalancesAPI {
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEmpCurrentPettyCashBalancesDeleteEmpCurrentPettyCashBalanceIdDelete(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiEmpCurrentPettyCashBalancesDeleteEmpCurrentPettyCashBalanceIdDeleteWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /api/EmpCurrentPettyCashBalances/DeleteEmpCurrentPettyCashBalance/{id}
     - 

     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func apiEmpCurrentPettyCashBalancesDeleteEmpCurrentPettyCashBalanceIdDeleteWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/api/EmpCurrentPettyCashBalances/DeleteEmpCurrentPettyCashBalance/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEmpCurrentPettyCashBalancesGetEmpCashBalanceVsAdvancedIdGet(_id: Int, completion: @escaping ((_ data: CashbalVsAdvancedVM?,_ error: Error?) -> Void)) {
        apiEmpCurrentPettyCashBalancesGetEmpCashBalanceVsAdvancedIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/EmpCurrentPettyCashBalances/GetEmpCashBalanceVsAdvanced/{id}
     - 

     - examples: [{contentType=application/json, example={
  "curCashBal" : 0.8008281904610115,
  "maxCashAllowed" : 6.027456183070403
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<CashbalVsAdvancedVM> 
     */
    open class func apiEmpCurrentPettyCashBalancesGetEmpCashBalanceVsAdvancedIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<CashbalVsAdvancedVM> {
        var path = "/api/EmpCurrentPettyCashBalances/GetEmpCashBalanceVsAdvanced/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<CashbalVsAdvancedVM>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEmpCurrentPettyCashBalancesGetEmpCurrentPettyCashBalanceIdGet(_id: Int, completion: @escaping ((_ data: EmpCurrentPettyCashBalanceDTO?,_ error: Error?) -> Void)) {
        apiEmpCurrentPettyCashBalancesGetEmpCurrentPettyCashBalanceIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/EmpCurrentPettyCashBalances/GetEmpCurrentPettyCashBalance/{id}
     - 

     - examples: [{contentType=application/json, example={
  "curBalance" : 1.4658129805029452,
  "employeeId" : 6,
  "id" : 0,
  "updatedOn" : "2000-01-23T04:56:07.000+00:00"
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<EmpCurrentPettyCashBalanceDTO> 
     */
    open class func apiEmpCurrentPettyCashBalancesGetEmpCurrentPettyCashBalanceIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<EmpCurrentPettyCashBalanceDTO> {
        
//    https://fwserver.atocash.tk/api/EmpCurrentCashAdvanceBalances/GetEmpCashBalanceVsAdvanced/40005
        var path = "/api/EmpCurrentCashAdvanceBalances/GetEmpMaxlimitcurBalAndCashInHandStatus/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<EmpCurrentPettyCashBalanceDTO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEmpCurrentPettyCashBalancesGetEmpCurrentPettyCashBalancesGet(completion: @escaping ((_ data: [EmpCurrentPettyCashBalanceDTO]?,_ error: Error?) -> Void)) {
        apiEmpCurrentPettyCashBalancesGetEmpCurrentPettyCashBalancesGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/EmpCurrentPettyCashBalances/GetEmpCurrentPettyCashBalances
     - 

     - examples: [{contentType=application/json, example=[ {
  "curBalance" : 1.4658129805029452,
  "employeeId" : 6,
  "id" : 0,
  "updatedOn" : "2000-01-23T04:56:07.000+00:00"
}, {
  "curBalance" : 1.4658129805029452,
  "employeeId" : 6,
  "id" : 0,
  "updatedOn" : "2000-01-23T04:56:07.000+00:00"
} ]}]

     - returns: RequestBuilder<[EmpCurrentPettyCashBalanceDTO]> 
     */
    open class func apiEmpCurrentPettyCashBalancesGetEmpCurrentPettyCashBalancesGetWithRequestBuilder() -> RequestBuilder<[EmpCurrentPettyCashBalanceDTO]> {
        let path = "/api/EmpCurrentPettyCashBalances/GetEmpCurrentPettyCashBalances"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[EmpCurrentPettyCashBalanceDTO]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEmpCurrentPettyCashBalancesGetEmpMaxlimitCurBalAndCashInHandStatusIdGet(_id: Int, completion: @escaping ((_ data: EmpAllCurBalStatusDTO?,_ error: Error?) -> Void)) {
        apiEmpCurrentPettyCashBalancesGetEmpMaxlimitCurBalAndCashInHandStatusIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/EmpCurrentPettyCashBalances/GetEmpMaxlimitCurBalAndCashInHandStatus/{id}
     - 

     - examples: [{contentType=application/json, example={
  "totalAmountToWallet" : 5.637376656633329,
  "cashInHand" : 1.4658129805029452,
  "maxLimit" : 0.8008281904610115,
  "curBalance" : 6.027456183070403,
  "walletBalLastUpdated" : "2000-01-23T04:56:07.000+00:00",
  "totalAmountToCredit" : 5.962133916683182
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<EmpAllCurBalStatusDTO> 
     */
    open class func apiEmpCurrentPettyCashBalancesGetEmpMaxlimitCurBalAndCashInHandStatusIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<EmpAllCurBalStatusDTO> {
        var path = "/api/EmpCurrentPettyCashBalances/GetEmpMaxlimitCurBalAndCashInHandStatus/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<EmpAllCurBalStatusDTO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEmpCurrentPettyCashBalancesPostEmpCurrentPettyCashBalancePost(body: EmpCurrentPettyCashBalanceDTO? = nil, completion: @escaping ((_ data: EmpCurrentPettyCashBalance?,_ error: Error?) -> Void)) {
        apiEmpCurrentPettyCashBalancesPostEmpCurrentPettyCashBalancePostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/EmpCurrentPettyCashBalances/PostEmpCurrentPettyCashBalance
     - 

     - examples: [{contentType=application/json, example={
  "curBalance" : 1.4658129805029452,
  "employeeId" : 6,
  "id" : 0,
  "updatedOn" : "2000-01-23T04:56:07.000+00:00",
  "employee" : {
    "currencyType" : {
      "country" : "country",
      "currencyName" : "currencyName",
      "statusTypeId" : 1,
      "id" : 1,
      "currencyCode" : "currencyCode"
    },
    "lastName" : "lastName",
    "approvalGroup" : {
      "approvalGroupDesc" : "approvalGroupDesc",
      "approvalGroupCode" : "approvalGroupCode",
      "id" : 0
    },
    "role" : {
      "roleCode" : "roleCode",
      "roleName" : "roleName",
      "id" : 1,
      "maxPettyCashAllowed" : 5.962133916683182
    },
    "gender" : "gender",
    "mobileNumber" : "mobileNumber",
    "departmentId" : 4,
    "statusTypeId" : 7,
    "nationalID" : "nationalID",
    "id" : 6,
    "department" : {
      "deptName" : "deptName",
      "costCenterId" : 3,
      "costCenter" : {
        "costCenterCode" : "costCenterCode",
        "statusType" : {
          "id" : 7,
          "status" : "status"
        },
        "statusTypeId" : 9,
        "id" : 2,
        "costCenterDesc" : "costCenterDesc"
      },
      "statusTypeId" : 2,
      "id" : 5,
      "deptCode" : "deptCode"
    },
    "email" : "",
    "bankAccount" : "bankAccount",
    "passportNo" : "passportNo",
    "bankCardNo" : "bankCardNo",
    "employmentType" : {
      "empJobTypeCode" : "empJobTypeCode",
      "id" : 1,
      "empJobTypeDesc" : "empJobTypeDesc"
    },
    "roleId" : 7,
    "taxNumber" : "taxNumber",
    "currencyTypeId" : 6,
    "firstName" : "firstName",
    "nationality" : "nationality",
    "empCode" : "empCode",
    "employmentTypeId" : 5,
    "dob" : "2000-01-23T04:56:07.000+00:00",
    "approvalGroupId" : 1,
    "middleName" : "middleName",
    "doj" : "2000-01-23T04:56:07.000+00:00"
  }
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<EmpCurrentPettyCashBalance> 
     */
    open class func apiEmpCurrentPettyCashBalancesPostEmpCurrentPettyCashBalancePostWithRequestBuilder(body: EmpCurrentPettyCashBalanceDTO? = nil) -> RequestBuilder<EmpCurrentPettyCashBalance> {
        let path = "/api/EmpCurrentPettyCashBalances/PostEmpCurrentPettyCashBalance"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<EmpCurrentPettyCashBalance>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter _id: (path)  
     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiEmpCurrentPettyCashBalancesPutEmpCurrentPettyCashBalanceIdPut(_id: Int, body: EmpCurrentPettyCashBalanceDTO? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiEmpCurrentPettyCashBalancesPutEmpCurrentPettyCashBalanceIdPutWithRequestBuilder(_id: _id, body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PUT /api/EmpCurrentPettyCashBalances/PutEmpCurrentPettyCashBalance/{id}
     - 

     - parameter _id: (path)  
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiEmpCurrentPettyCashBalancesPutEmpCurrentPettyCashBalanceIdPutWithRequestBuilder(_id: Int, body: EmpCurrentPettyCashBalanceDTO? = nil) -> RequestBuilder<Void> {
        var path = "/api/EmpCurrentPettyCashBalances/PutEmpCurrentPettyCashBalance/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
