//
// TravelApprovalStatusTrackersAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire


open class TravelApprovalStatusTrackersAPI {
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTravelApprovalStatusTrackersApprovalFlowForTravelRequestIdGet(_id: Int, completion: @escaping ((_ data: [ApprovalStatusFlowVM]?,_ error: Error?) -> Void)) {
        apiTravelApprovalStatusTrackersApprovalFlowForTravelRequestIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TravelApprovalStatusTrackers/ApprovalFlowForTravelRequest/{id}
     - 

     - examples: [{contentType=application/json, example=[ {
  "approvedDate" : "2000-01-23T04:56:07.000+00:00",
  "approverRole" : "approverRole",
  "approvalLevel" : 0,
  "approvalStatusType" : "approvalStatusType",
  "approverName" : "approverName"
}, {
  "approvedDate" : "2000-01-23T04:56:07.000+00:00",
  "approverRole" : "approverRole",
  "approvalLevel" : 0,
  "approvalStatusType" : "approvalStatusType",
  "approverName" : "approverName"
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[ApprovalStatusFlowVM]> 
     */
    open class func apiTravelApprovalStatusTrackersApprovalFlowForTravelRequestIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<[ApprovalStatusFlowVM]> {
        var path = "/api/TravelApprovalStatusTrackers/ApprovalFlowForRequest/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[ApprovalStatusFlowVM]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTravelApprovalStatusTrackersApprovalsPendingForApproverIdGet(_id: Int, completion: @escaping ((_ data: [TravelApprovalStatusTrackerDTO]?,_ error: Error?) -> Void)) {
        apiTravelApprovalStatusTrackersApprovalsPendingForApproverIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TravelApprovalStatusTrackers/ApprovalsPendingForApprover/{id}
     - 

     - examples: [{contentType=application/json, example=[ {
  "departmentName" : "departmentName",
  "finalApprovedDate" : "2000-01-23T04:56:07.000+00:00",
  "employeeName" : "employeeName",
  "comments" : "comments",
  "roleId" : 7,
  "departmentId" : 5,
  "employeeId" : 6,
  "approvalStatusTypeId" : 3,
  "travelEndDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalLevelId" : 9,
  "reqDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalGroupId" : 2,
  "travelStartDate" : "2000-01-23T04:56:07.000+00:00",
  "jobRole" : "jobRole",
  "id" : 0,
  "travelApprovalRequestId" : 1,
  "projectName" : "projectName",
  "approvalStatusType" : "approvalStatusType",
  "projectId" : 5
}, {
  "departmentName" : "departmentName",
  "finalApprovedDate" : "2000-01-23T04:56:07.000+00:00",
  "employeeName" : "employeeName",
  "comments" : "comments",
  "roleId" : 7,
  "departmentId" : 5,
  "employeeId" : 6,
  "approvalStatusTypeId" : 3,
  "travelEndDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalLevelId" : 9,
  "reqDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalGroupId" : 2,
  "travelStartDate" : "2000-01-23T04:56:07.000+00:00",
  "jobRole" : "jobRole",
  "id" : 0,
  "travelApprovalRequestId" : 1,
  "projectName" : "projectName",
  "approvalStatusType" : "approvalStatusType",
  "projectId" : 5
} ]}]
     - parameter _id: (path)  

     - returns: RequestBuilder<[TravelApprovalStatusTrackerDTO]> 
     */
    open class func apiTravelApprovalStatusTrackersApprovalsPendingForApproverIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<[TravelApprovalStatusTrackerDTO]> {
        var path = "/api/TravelApprovalStatusTrackers/ApprovalsPendingForApprover/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[TravelApprovalStatusTrackerDTO]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTravelApprovalStatusTrackersCountOfApprovalsPendingForApproverIdGet(_id: Int, completion: @escaping ((_ data: Int?,_ error: Error?) -> Void)) {
        apiTravelApprovalStatusTrackersCountOfApprovalsPendingForApproverIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TravelApprovalStatusTrackers/CountOfApprovalsPendingForApprover/{id}
     - 

     - examples: [{contentType=application/json, example=0}]
     - parameter _id: (path)  

     - returns: RequestBuilder<Int> 
     */
    open class func apiTravelApprovalStatusTrackersCountOfApprovalsPendingForApproverIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<Int> {
        var path = "/api/TravelApprovalStatusTrackers/CountOfApprovalsPendingForApprover/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Int>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTravelApprovalStatusTrackersDeleteTravelApprovalStatusTrackerIdDelete(_id: Int, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiTravelApprovalStatusTrackersDeleteTravelApprovalStatusTrackerIdDeleteWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - DELETE /api/TravelApprovalStatusTrackers/DeleteTravelApprovalStatusTracker/{id}
     - 

     - parameter _id: (path)  

     - returns: RequestBuilder<Void> 
     */
    open class func apiTravelApprovalStatusTrackersDeleteTravelApprovalStatusTrackerIdDeleteWithRequestBuilder(_id: Int) -> RequestBuilder<Void> {
        var path = "/api/TravelApprovalStatusTrackers/DeleteTravelApprovalStatusTracker/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "DELETE", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter _id: (path)  
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTravelApprovalStatusTrackersGetTravelApprovalStatusTrackerIdGet(_id: Int, completion: @escaping ((_ data: TravelApprovalStatusTrackerDTO?,_ error: Error?) -> Void)) {
        apiTravelApprovalStatusTrackersGetTravelApprovalStatusTrackerIdGetWithRequestBuilder(_id: _id).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TravelApprovalStatusTrackers/GetTravelApprovalStatusTracker/{id}
     - 

     - examples: [{contentType=application/json, example={
  "departmentName" : "departmentName",
  "finalApprovedDate" : "2000-01-23T04:56:07.000+00:00",
  "employeeName" : "employeeName",
  "comments" : "comments",
  "roleId" : 7,
  "departmentId" : 5,
  "employeeId" : 6,
  "approvalStatusTypeId" : 3,
  "travelEndDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalLevelId" : 9,
  "reqDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalGroupId" : 2,
  "travelStartDate" : "2000-01-23T04:56:07.000+00:00",
  "jobRole" : "jobRole",
  "id" : 0,
  "travelApprovalRequestId" : 1,
  "projectName" : "projectName",
  "approvalStatusType" : "approvalStatusType",
  "projectId" : 5
}}]
     - parameter _id: (path)  

     - returns: RequestBuilder<TravelApprovalStatusTrackerDTO> 
     */
    open class func apiTravelApprovalStatusTrackersGetTravelApprovalStatusTrackerIdGetWithRequestBuilder(_id: Int) -> RequestBuilder<TravelApprovalStatusTrackerDTO> {
        var path = "/api/TravelApprovalStatusTrackers/GetTravelApprovalStatusTracker/{id}"
        let _idPreEscape = "\(_id)"
        let _idPostEscape = _idPreEscape.addingPercentEncoding(withAllowedCharacters: .urlPathAllowed) ?? ""
        path = path.replacingOccurrences(of: "{id}", with: _idPostEscape, options: .literal, range: nil)
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<TravelApprovalStatusTrackerDTO>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTravelApprovalStatusTrackersGetTravelApprovalStatusTrackersGet(completion: @escaping ((_ data: [TravelApprovalStatusTrackerDTO]?,_ error: Error?) -> Void)) {
        apiTravelApprovalStatusTrackersGetTravelApprovalStatusTrackersGetWithRequestBuilder().execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - GET /api/TravelApprovalStatusTrackers/GetTravelApprovalStatusTrackers
     - 

     - examples: [{contentType=application/json, example=[ {
  "departmentName" : "departmentName",
  "finalApprovedDate" : "2000-01-23T04:56:07.000+00:00",
  "employeeName" : "employeeName",
  "comments" : "comments",
  "roleId" : 7,
  "departmentId" : 5,
  "employeeId" : 6,
  "approvalStatusTypeId" : 3,
  "travelEndDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalLevelId" : 9,
  "reqDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalGroupId" : 2,
  "travelStartDate" : "2000-01-23T04:56:07.000+00:00",
  "jobRole" : "jobRole",
  "id" : 0,
  "travelApprovalRequestId" : 1,
  "projectName" : "projectName",
  "approvalStatusType" : "approvalStatusType",
  "projectId" : 5
}, {
  "departmentName" : "departmentName",
  "finalApprovedDate" : "2000-01-23T04:56:07.000+00:00",
  "employeeName" : "employeeName",
  "comments" : "comments",
  "roleId" : 7,
  "departmentId" : 5,
  "employeeId" : 6,
  "approvalStatusTypeId" : 3,
  "travelEndDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalLevelId" : 9,
  "reqDate" : "2000-01-23T04:56:07.000+00:00",
  "approvalGroupId" : 2,
  "travelStartDate" : "2000-01-23T04:56:07.000+00:00",
  "jobRole" : "jobRole",
  "id" : 0,
  "travelApprovalRequestId" : 1,
  "projectName" : "projectName",
  "approvalStatusType" : "approvalStatusType",
  "projectId" : 5
} ]}]

     - returns: RequestBuilder<[TravelApprovalStatusTrackerDTO]> 
     */
    open class func apiTravelApprovalStatusTrackersGetTravelApprovalStatusTrackersGetWithRequestBuilder() -> RequestBuilder<[TravelApprovalStatusTrackerDTO]> {
        let path = "/api/TravelApprovalStatusTrackers/GetTravelApprovalStatusTrackers"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters: [String:Any]? = nil
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<[TravelApprovalStatusTrackerDTO]>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTravelApprovalStatusTrackersPostTravelApprovalStatusTrackerPost(body: TravelApprovalStatusTracker? = nil, completion: @escaping ((_ data: TravelApprovalStatusTracker?,_ error: Error?) -> Void)) {
        apiTravelApprovalStatusTrackersPostTravelApprovalStatusTrackerPostWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(response?.body, error)
        }
    }


    /**
     - POST /api/TravelApprovalStatusTrackers/PostTravelApprovalStatusTracker
     - 

     - examples: [{contentType=application/json, example={
  "finalApprovedDate" : "2000-01-23T04:56:07.000+00:00",
  "role" : {
    "roleCode" : "roleCode",
    "roleName" : "roleName",
    "id" : 1,
    "maxPettyCashAllowed" : 5.962133916683182
  },
  "workTaskId" : 9,
  "departmentId" : 5,
  "project" : {
    "costCenterId" : 9,
    "statusTypeId" : 3,
    "projectManagerId" : 6,
    "projectDesc" : "projectDesc",
    "id" : 8,
    "projectName" : "projectName"
  },
  "approvalStatusTypeId" : 7,
  "employee" : {
    "currencyType" : {
      "country" : "country",
      "currencyName" : "currencyName",
      "statusTypeId" : 1,
      "id" : 1,
      "currencyCode" : "currencyCode"
    },
    "lastName" : "lastName",
    "approvalGroup" : {
      "approvalGroupDesc" : "approvalGroupDesc",
      "approvalGroupCode" : "approvalGroupCode",
      "id" : 0
    },
    "role" : {
      "roleCode" : "roleCode",
      "roleName" : "roleName",
      "id" : 1,
      "maxPettyCashAllowed" : 5.962133916683182
    },
    "gender" : "gender",
    "mobileNumber" : "mobileNumber",
    "departmentId" : 4,
    "statusTypeId" : 7,
    "nationalID" : "nationalID",
    "id" : 6,
    "department" : {
      "deptName" : "deptName",
      "costCenterId" : 3,
      "costCenter" : {
        "costCenterCode" : "costCenterCode",
        "statusType" : {
          "id" : 7,
          "status" : "status"
        },
        "statusTypeId" : 9,
        "id" : 2,
        "costCenterDesc" : "costCenterDesc"
      },
      "statusTypeId" : 2,
      "id" : 5,
      "deptCode" : "deptCode"
    },
    "email" : "",
    "bankAccount" : "bankAccount",
    "passportNo" : "passportNo",
    "bankCardNo" : "bankCardNo",
    "employmentType" : {
      "empJobTypeCode" : "empJobTypeCode",
      "id" : 1,
      "empJobTypeDesc" : "empJobTypeDesc"
    },
    "roleId" : 7,
    "taxNumber" : "taxNumber",
    "currencyTypeId" : 6,
    "firstName" : "firstName",
    "nationality" : "nationality",
    "empCode" : "empCode",
    "employmentTypeId" : 5,
    "dob" : "2000-01-23T04:56:07.000+00:00",
    "approvalGroupId" : 1,
    "middleName" : "middleName",
    "doj" : "2000-01-23T04:56:07.000+00:00"
  },
  "approvalLevelId" : 4,
  "reqDate" : "2000-01-23T04:56:07.000+00:00",
  "travelStartDate" : "2000-01-23T04:56:07.000+00:00",
  "id" : 0,
  "department" : {
    "deptName" : "deptName",
    "costCenterId" : 3,
    "costCenter" : {
      "costCenterCode" : "costCenterCode",
      "statusType" : {
        "id" : 7,
        "status" : "status"
      },
      "statusTypeId" : 9,
      "id" : 2,
      "costCenterDesc" : "costCenterDesc"
    },
    "statusTypeId" : 2,
    "id" : 5,
    "deptCode" : "deptCode"
  },
  "comments" : "comments",
  "workTask" : {
    "taskDesc" : "taskDesc",
    "subProjectId" : 5,
    "taskName" : "taskName",
    "id" : 6
  },
  "roleId" : 2,
  "employeeId" : 6,
  "travelEndDate" : "2000-01-23T04:56:07.000+00:00",
  "travelApprovalRequest" : {
    "comments" : "comments",
    "workTask" : {
      "taskDesc" : "taskDesc",
      "subProjectId" : 5,
      "taskName" : "taskName",
      "id" : 6
    },
    "workTaskId" : 2,
    "costCenter" : {
      "costCenterCode" : "costCenterCode",
      "statusType" : {
        "id" : 7,
        "status" : "status"
      },
      "statusTypeId" : 9,
      "id" : 2,
      "costCenterDesc" : "costCenterDesc"
    },
    "departmentId" : 1,
    "project" : {
      "costCenterId" : 9,
      "statusTypeId" : 3,
      "projectManagerId" : 6,
      "projectDesc" : "projectDesc",
      "id" : 8,
      "projectName" : "projectName"
    },
    "employeeId" : 6,
    "travelPurpose" : "travelPurpose",
    "approvalStatusTypeId" : 9,
    "employee" : {
      "currencyType" : {
        "country" : "country",
        "currencyName" : "currencyName",
        "statusTypeId" : 1,
        "id" : 1,
        "currencyCode" : "currencyCode"
      },
      "lastName" : "lastName",
      "approvalGroup" : {
        "approvalGroupDesc" : "approvalGroupDesc",
        "approvalGroupCode" : "approvalGroupCode",
        "id" : 0
      },
      "role" : {
        "roleCode" : "roleCode",
        "roleName" : "roleName",
        "id" : 1,
        "maxPettyCashAllowed" : 5.962133916683182
      },
      "gender" : "gender",
      "mobileNumber" : "mobileNumber",
      "departmentId" : 4,
      "statusTypeId" : 7,
      "nationalID" : "nationalID",
      "id" : 6,
      "department" : {
        "deptName" : "deptName",
        "costCenterId" : 3,
        "costCenter" : {
          "costCenterCode" : "costCenterCode",
          "statusType" : {
            "id" : 7,
            "status" : "status"
          },
          "statusTypeId" : 9,
          "id" : 2,
          "costCenterDesc" : "costCenterDesc"
        },
        "statusTypeId" : 2,
        "id" : 5,
        "deptCode" : "deptCode"
      },
      "email" : "",
      "bankAccount" : "bankAccount",
      "passportNo" : "passportNo",
      "bankCardNo" : "bankCardNo",
      "employmentType" : {
        "empJobTypeCode" : "empJobTypeCode",
        "id" : 1,
        "empJobTypeDesc" : "empJobTypeDesc"
      },
      "roleId" : 7,
      "taxNumber" : "taxNumber",
      "currencyTypeId" : 6,
      "firstName" : "firstName",
      "nationality" : "nationality",
      "empCode" : "empCode",
      "employmentTypeId" : 5,
      "dob" : "2000-01-23T04:56:07.000+00:00",
      "approvalGroupId" : 1,
      "middleName" : "middleName",
      "doj" : "2000-01-23T04:56:07.000+00:00"
    },
    "travelEndDate" : "2000-01-23T04:56:07.000+00:00",
    "approvedDate" : "2000-01-23T04:56:07.000+00:00",
    "costCenterId" : 7,
    "travelStartDate" : "2000-01-23T04:56:07.000+00:00",
    "subProjectId" : 5,
    "subProject" : {
      "subProjectName" : "subProjectName",
      "subProjectDesc" : "subProjectDesc",
      "id" : 1,
      "projectId" : 2
    },
    "id" : 0,
    "department" : {
      "deptName" : "deptName",
      "costCenterId" : 3,
      "costCenter" : {
        "costCenterCode" : "costCenterCode",
        "statusType" : {
          "id" : 7,
          "status" : "status"
        },
        "statusTypeId" : 9,
        "id" : 2,
        "costCenterDesc" : "costCenterDesc"
      },
      "statusTypeId" : 2,
      "id" : 5,
      "deptCode" : "deptCode"
    },
    "approvalStatusType" : {
      "statusDesc" : "statusDesc",
      "id" : 0,
      "status" : "status"
    },
    "reqRaisedDate" : "2000-01-23T04:56:07.000+00:00",
    "projectId" : 5
  },
  "approvalGroupId" : 3,
  "subProjectId" : 7,
  "subProject" : {
    "subProjectName" : "subProjectName",
    "subProjectDesc" : "subProjectDesc",
    "id" : 1,
    "projectId" : 2
  },
  "travelApprovalRequestId" : 1,
  "approvalLevel" : {
    "level" : 6,
    "levelDesc" : "levelDesc",
    "id" : 0
  },
  "approvalStatusType" : {
    "statusDesc" : "statusDesc",
    "id" : 0,
    "status" : "status"
  },
  "projManagerId" : 5,
  "projectId" : 2
}}]
     - parameter body: (body)  (optional)

     - returns: RequestBuilder<TravelApprovalStatusTracker> 
     */
    open class func apiTravelApprovalStatusTrackersPostTravelApprovalStatusTrackerPostWithRequestBuilder(body: TravelApprovalStatusTracker? = nil) -> RequestBuilder<TravelApprovalStatusTracker> {
        let path = "/api/TravelApprovalStatusTrackers/PostTravelApprovalStatusTracker"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<TravelApprovalStatusTracker>.Type = SwaggerClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
    /**

     - parameter body: (body)  (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func apiTravelApprovalStatusTrackersPutTravelApprovalStatusTrackerPut(body: [TravelApprovalStatusTrackerDTO]? = nil, completion: @escaping ((_ data: Void?,_ error: Error?) -> Void)) {
        apiTravelApprovalStatusTrackersPutTravelApprovalStatusTrackerPutWithRequestBuilder(body: body).execute { (response, error) -> Void in
            if error == nil {
                completion((), error)
            } else {
                completion(nil, error)
            }
        }
    }


    /**
     - PUT /api/TravelApprovalStatusTrackers/PutTravelApprovalStatusTracker
     - 

     - parameter body: (body)  (optional)

     - returns: RequestBuilder<Void> 
     */
    open class func apiTravelApprovalStatusTrackersPutTravelApprovalStatusTrackerPutWithRequestBuilder(body: [TravelApprovalStatusTrackerDTO]? = nil) -> RequestBuilder<Void> {
        let path = "/api/TravelApprovalStatusTrackers/PutTravelApprovalStatusTracker"
        let URLString = SwaggerClientAPI.basePath + path
        let parameters = JSONEncodingHelper.encodingParameters(forEncodableObject: body)
        let url = URLComponents(string: URLString)


        let requestBuilder: RequestBuilder<Void>.Type = SwaggerClientAPI.requestBuilderFactory.getNonDecodableBuilder()

        return requestBuilder.init(method: "PUT", URLString: (url?.string ?? URLString), parameters: parameters, isBody: true)
    }
}
